version: "3.9"
services:
  db:
    image: postgres:16
    container_name: wallet-db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d wallet_db" ]
      interval: 3s
      timeout: 3s
      retries: 20

  app:
    build: .
    container_name: wallet-app
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    ports:
      - "8080:8080"
volumes:
  db_data:
